version: "3.3"  # optional since v1.27.0
services:
  baidunetdisksync:
    build: .
    container_name: bdnd_tools
    environment:
      TZ: "Asia/Shanghai"
      PYTHONIOENCODING: "utf8"
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    volumes:
      - ./data:/data/

    restart: always
